### ISSUE TITLE
add --patch as an alias to --bugfix

### ISSUE THREAD

**Issue by ryanramage** [sdepold/release-tools#8]
I have been trying this out today. It's handy!

One suggestion, i keep trying this:

    npm_release --patch

Because i need to bump the last number, the patch. Could --patch be added, and it be equivalent to  --bugfix for backwards compat?

**Comment by sdepold** [comment]
Sure!

**Comment by sdepold** [comment]
Btw you can also do npm_release patch

**Comment by sdepold** [comment]
just released 2.4.2 which fixes this issue.
